GET http://localhost:3000/alumnos


###

GET http://localhost:3000/alumnos/1003


###


GET http://localhost:3000/docentes


###


GET http://localhost:3000/docentes/5


###

POST http://localhost:3000/alumnos
Content-Type: application/json

{
    "legajo" : 1010,
    "nombre" : "Shadow",
    "carrera" : "the Hedgehog",
    "correo": "shadow2edgy@gmail.com"
}


###

PUT http://localhost:3000/alumnos/1004
Content-Type: application/json

{
    "legajo" : 1004,
    "nombre" : "JuanPumbas",
    "carrera" : "CS",
    "correo" : "blasfemiah@mijo.cum"
}
###

GET  http://localhost:3000/alumnos/2


###

DELETE http://localhost:3000/alumnos/1010


###

GET http://localhost:3000/alumnos



###
    
POST http://localhost:3000/alumnos
Content-Type: application/json

{
}