GET http://localhost:3000/alumnos


###

GET http://localhost:3000/alumnos/20


###


GET http://localhost:3000/docentes


###


GET http://localhost:3000/docentes/5


###

POST http://localhost:3000/alumnos
Content-Type: application/json

{
    "id" : 8,
    "nombre" : "Sonic",
    "carrera" : "Adventure"
}


###

PUT http://localhost:3000/alumnos/1
Content-Type: application/json

{
    "id" : 2,
    "nombre" : "JuanPerez",
    "carrera" : "Prooo"
}
###

GET  http://localhost:3000/alumnos/2


###

DELETE http://localhost:3000/alumnos/5


###

GET http://localhost:3000/alumnos



###
    
POST http://localhost:3000/alumnos
Content-Type: application/json

{
}